// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/quote": {
    params: {};
  };
  "/agent-portal": {
    params: {};
  };
  "/SignUp": {
    params: {};
  };
  "/verify-otp": {
    params: {};
  };
  "/Proceed-Otp": {
    params: {};
  };
  "/claims": {
    params: {};
  };
  "/blogs": {
    params: {};
  };
  "/blogs/:slug": {
    params: {
      "slug": string;
    };
  };
  "/contact-us": {
    params: {};
  };
  "/terms-and-conditions": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/refund-policy": {
    params: {};
  };
  "/client-portal": {
    params: {};
  };
  "/agent-portal-profile": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/quote" | "/agent-portal" | "/SignUp" | "/verify-otp" | "/Proceed-Otp" | "/claims" | "/blogs" | "/blogs/:slug" | "/contact-us" | "/terms-and-conditions" | "/privacy-policy" | "/refund-policy" | "/client-portal" | "/agent-portal-profile";
  };
  "./layouts/MainLayouts.tsx": {
    id: "layouts/MainLayouts";
    page: "/" | "/about" | "/quote" | "/agent-portal" | "/SignUp" | "/verify-otp" | "/Proceed-Otp" | "/claims" | "/blogs" | "/blogs/:slug" | "/contact-us" | "/terms-and-conditions" | "/privacy-policy" | "/refund-policy";
  };
  "./routes/Home.tsx": {
    id: "routes/Home";
    page: "/";
  };
  "./routes/About.tsx": {
    id: "routes/About";
    page: "/about";
  };
  "./routes/Quote.tsx": {
    id: "routes/Quote";
    page: "/quote";
  };
  "./routes/AgentPortal.tsx": {
    id: "routes/AgentPortal";
    page: "/agent-portal";
  };
  "./routes/SignUp.tsx": {
    id: "routes/SignUp";
    page: "/SignUp";
  };
  "./routes/VerifyOtp.tsx": {
    id: "routes/VerifyOtp";
    page: "/verify-otp";
  };
  "./routes/ProceedOtp.tsx": {
    id: "routes/ProceedOtp";
    page: "/Proceed-Otp";
  };
  "./routes/Claims.tsx": {
    id: "routes/Claims";
    page: "/claims";
  };
  "./routes/Blogs.tsx": {
    id: "routes/Blogs";
    page: "/blogs";
  };
  "./routes/BlogArticle.tsx": {
    id: "routes/BlogArticle";
    page: "/blogs/:slug";
  };
  "./routes/ContactUs.tsx": {
    id: "routes/ContactUs";
    page: "/contact-us";
  };
  "./routes/TermsAndConditions.tsx": {
    id: "routes/TermsAndConditions";
    page: "/terms-and-conditions";
  };
  "./routes/PrivacyPolicy.tsx": {
    id: "routes/PrivacyPolicy";
    page: "/privacy-policy";
  };
  "./routes/RefundPolicy.tsx": {
    id: "routes/RefundPolicy";
    page: "/refund-policy";
  };
  "./routes/Clientportallogin.tsx": {
    id: "routes/Clientportallogin";
    page: "/client-portal";
  };
  "./routes/AgentPortalProfile.tsx": {
    id: "routes/AgentPortalProfile";
    page: "/agent-portal-profile";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "layouts/MainLayouts": typeof import("./app/./layouts/MainLayouts.tsx");
  "routes/Home": typeof import("./app/./routes/Home.tsx");
  "routes/About": typeof import("./app/./routes/About.tsx");
  "routes/Quote": typeof import("./app/./routes/Quote.tsx");
  "routes/AgentPortal": typeof import("./app/./routes/AgentPortal.tsx");
  "routes/SignUp": typeof import("./app/./routes/SignUp.tsx");
  "routes/VerifyOtp": typeof import("./app/./routes/VerifyOtp.tsx");
  "routes/ProceedOtp": typeof import("./app/./routes/ProceedOtp.tsx");
  "routes/Claims": typeof import("./app/./routes/Claims.tsx");
  "routes/Blogs": typeof import("./app/./routes/Blogs.tsx");
  "routes/BlogArticle": typeof import("./app/./routes/BlogArticle.tsx");
  "routes/ContactUs": typeof import("./app/./routes/ContactUs.tsx");
  "routes/TermsAndConditions": typeof import("./app/./routes/TermsAndConditions.tsx");
  "routes/PrivacyPolicy": typeof import("./app/./routes/PrivacyPolicy.tsx");
  "routes/RefundPolicy": typeof import("./app/./routes/RefundPolicy.tsx");
  "routes/Clientportallogin": typeof import("./app/./routes/Clientportallogin.tsx");
  "routes/AgentPortalProfile": typeof import("./app/./routes/AgentPortalProfile.tsx");
};